// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectZero.Database;

#nullable disable

namespace ProjectZero.Database.Migrations
{
    [DbContext(typeof(TvShowDbContext))]
    [Migration("20260614150145_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenreEntityTvShowEntity", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<int>("TvShowsId")
                        .HasColumnType("integer");

                    b.HasKey("GenresId", "TvShowsId");

                    b.HasIndex("TvShowsId");

                    b.ToTable("TvShowGenres", (string)null);
                });

            modelBuilder.Entity("ProjectZero.Database.Entities.DirectorEntity", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("TvShowId")
                        .HasColumnType("integer");

                    b.HasKey("PersonId", "TvShowId");

                    b.HasIndex("TvShowId");

                    b.ToTable("Directors", (string)null);
                });

            modelBuilder.Entity("ProjectZero.Database.Entities.GenreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres", (string)null);
                });

            modelBuilder.Entity("ProjectZero.Database.Entities.PersonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("ProjectZero.Database.Entities.StarEntity", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("TvShowId")
                        .HasColumnType("integer");

                    b.HasKey("PersonId", "TvShowId");

                    b.HasIndex("TvShowId");

                    b.ToTable("Stars", (string)null);
                });

            modelBuilder.Entity("ProjectZero.Database.Entities.TvShowEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Episodes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateOnly?>("ReleasedAt")
                        .HasColumnType("date");

                    b.Property<int>("Seasons")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TvShows", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Episodes = 62,
                            Name = "Breaking Bad",
                            ReleasedAt = new DateOnly(2008, 1, 20),
                            Seasons = 5
                        },
                        new
                        {
                            Id = 2,
                            Episodes = 16,
                            Name = "The Last of Us",
                            ReleasedAt = new DateOnly(2023, 1, 15),
                            Seasons = 2
                        });
                });

            modelBuilder.Entity("ProjectZero.Database.Entities.WriterEntity", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("TvShowId")
                        .HasColumnType("integer");

                    b.HasKey("PersonId", "TvShowId");

                    b.HasIndex("TvShowId");

                    b.ToTable("Writers", (string)null);
                });

            modelBuilder.Entity("GenreEntityTvShowEntity", b =>
                {
                    b.HasOne("ProjectZero.Database.Entities.GenreEntity", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectZero.Database.Entities.TvShowEntity", null)
                        .WithMany()
                        .HasForeignKey("TvShowsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectZero.Database.Entities.DirectorEntity", b =>
                {
                    b.HasOne("ProjectZero.Database.Entities.PersonEntity", "Person")
                        .WithMany("DirectorRoles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectZero.Database.Entities.TvShowEntity", "TvShow")
                        .WithMany("Directors")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("TvShow");
                });

            modelBuilder.Entity("ProjectZero.Database.Entities.StarEntity", b =>
                {
                    b.HasOne("ProjectZero.Database.Entities.PersonEntity", "Person")
                        .WithMany("StarRoles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectZero.Database.Entities.TvShowEntity", "TvShow")
                        .WithMany("Stars")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("TvShow");
                });

            modelBuilder.Entity("ProjectZero.Database.Entities.WriterEntity", b =>
                {
                    b.HasOne("ProjectZero.Database.Entities.PersonEntity", "Person")
                        .WithMany("WriterRoles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectZero.Database.Entities.TvShowEntity", "TvShow")
                        .WithMany("Writers")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("TvShow");
                });

            modelBuilder.Entity("ProjectZero.Database.Entities.PersonEntity", b =>
                {
                    b.Navigation("DirectorRoles");

                    b.Navigation("StarRoles");

                    b.Navigation("WriterRoles");
                });

            modelBuilder.Entity("ProjectZero.Database.Entities.TvShowEntity", b =>
                {
                    b.Navigation("Directors");

                    b.Navigation("Stars");

                    b.Navigation("Writers");
                });
#pragma warning restore 612, 618
        }
    }
}
