// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectZero.Database;

#nullable disable

namespace ProjectZero.Database.Migrations
{
    [DbContext(typeof(TvShowDbContext))]
    partial class TvShowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DirectorDaoTvShowDao", b =>
                {
                    b.Property<int>("DirectorsId")
                        .HasColumnType("integer");

                    b.Property<int>("TvShowsId")
                        .HasColumnType("integer");

                    b.HasKey("DirectorsId", "TvShowsId");

                    b.HasIndex("TvShowsId");

                    b.ToTable("TvShowDirectors", (string)null);
                });

            modelBuilder.Entity("GenreDaoTvShowDao", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<int>("TvShowsId")
                        .HasColumnType("integer");

                    b.HasKey("GenresId", "TvShowsId");

                    b.HasIndex("TvShowsId");

                    b.ToTable("TvShowGenres", (string)null);
                });

            modelBuilder.Entity("ProjectZero.Database.Daos.DirectorDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Directors");
                });

            modelBuilder.Entity("ProjectZero.Database.Daos.GenreDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("ProjectZero.Database.Daos.StarDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Stars");
                });

            modelBuilder.Entity("ProjectZero.Database.Daos.TvShowDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Episodes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateOnly?>("ReleasedAt")
                        .HasColumnType("date");

                    b.Property<int>("Seasons")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TvShows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Episodes = 62,
                            Name = "Breaking Bad",
                            ReleasedAt = new DateOnly(2008, 1, 20),
                            Seasons = 5
                        },
                        new
                        {
                            Id = 2,
                            Episodes = 16,
                            Name = "The Last of Us",
                            ReleasedAt = new DateOnly(2023, 1, 15),
                            Seasons = 2
                        });
                });

            modelBuilder.Entity("ProjectZero.Database.Daos.WriterDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Writers");
                });

            modelBuilder.Entity("StarDaoTvShowDao", b =>
                {
                    b.Property<int>("StarsId")
                        .HasColumnType("integer");

                    b.Property<int>("TvShowsId")
                        .HasColumnType("integer");

                    b.HasKey("StarsId", "TvShowsId");

                    b.HasIndex("TvShowsId");

                    b.ToTable("TvShowStars", (string)null);
                });

            modelBuilder.Entity("TvShowDaoWriterDao", b =>
                {
                    b.Property<int>("TvShowsId")
                        .HasColumnType("integer");

                    b.Property<int>("WritersId")
                        .HasColumnType("integer");

                    b.HasKey("TvShowsId", "WritersId");

                    b.HasIndex("WritersId");

                    b.ToTable("TvShowWriters", (string)null);
                });

            modelBuilder.Entity("DirectorDaoTvShowDao", b =>
                {
                    b.HasOne("ProjectZero.Database.Daos.DirectorDao", null)
                        .WithMany()
                        .HasForeignKey("DirectorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectZero.Database.Daos.TvShowDao", null)
                        .WithMany()
                        .HasForeignKey("TvShowsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreDaoTvShowDao", b =>
                {
                    b.HasOne("ProjectZero.Database.Daos.GenreDao", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectZero.Database.Daos.TvShowDao", null)
                        .WithMany()
                        .HasForeignKey("TvShowsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarDaoTvShowDao", b =>
                {
                    b.HasOne("ProjectZero.Database.Daos.StarDao", null)
                        .WithMany()
                        .HasForeignKey("StarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectZero.Database.Daos.TvShowDao", null)
                        .WithMany()
                        .HasForeignKey("TvShowsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TvShowDaoWriterDao", b =>
                {
                    b.HasOne("ProjectZero.Database.Daos.TvShowDao", null)
                        .WithMany()
                        .HasForeignKey("TvShowsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectZero.Database.Daos.WriterDao", null)
                        .WithMany()
                        .HasForeignKey("WritersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
