<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjectZero.TvShows.Application\ProjectZero.TvShows.Application.csproj" />
    <ProjectReference Include="..\ProjectZero.TvShows.Domain\ProjectZero.TvShows.Domain.csproj" />
    <ProjectReference Include="..\ProjectZero.TvShows.Infrastructure\ProjectZero.TvShows.Infrastructure.csproj" />
  </ItemGroup>

</Project>
